version: '2'
services:
    webtask-app:
        image: webtask
        external_links:
            - webtask-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/webtask?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    webtask-mysql:
        extends:
            file: mysql.yml
            service: webtask-mysql
